# Generated by Django 4.0.4 on 2022-05-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrit', '0002_alter_a_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_user',
            name='darkmode',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
