# Generated by Django 4.0.4 on 2022-05-09 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('barrit', '0005_alter_a_user_audiodescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='a_user',
            name='audiodescription',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='a_user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
