# Generated by Django 4.0.4 on 2022-05-09 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('barrit', '0006_a_user_uuid_alter_a_user_audiodescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_user',
            name='id',
        ),
        migrations.AlterField(
            model_name='a_user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
