export { default as About } from './About';
export { default as Home } from './Home';
export { default as Settings } from './Settings';
export { default as NotFound } from './NotFound';
export { default as PreviousSearch } from './PreviousSearch';
export { default as LoginPage } from './Login';
export { default as LogoutPage } from './Logout';
export { default as SignUp } from './SignUp';
export { default as Dashboard } from './Dashboard';
